// @scholia/db — Drizzle schema + client for scholia's mutable metadata.
export * as schema from "./schema.js";
export * from "./schema.js";
export { createDb, type Db } from "./client.js";
export {
  createSiteWithVersion,
  getSiteBySlug,
  getLatestPage,
  getLatestManifest,
  mintViewer,
  getViewer,
  getLatestVersionId,
  createConversation,
  addComment,
  editComment,
  deleteComment,
  tombstoneComment,
  detachMirror,
  ownerDeleteComment,
  setResolved,
  toggleReaction,
  listConversationsForPage,
  listChats,
  getConversationMeta,
  getCommentConversation,
  promoteConversation,
  mintViewerToken,
  resolveViewerToken,
  setSiteState,
  deleteSite,
  ownerDeleteConversation,
  rotateSlug,
  rotateOwnerToken,
  listTokens,
  revokeToken,
  listSiteComments,
  getManifestByOrdinal,
  listVersions,
  verifyOwnerToken,
  addVersionWithManifest,
  listConversationsForMigration,
  updateAnchorAfterMigration,
  getLastSeenOrdinal,
  setLastSeen,
  summaryForViewer,
  type CreateSiteInput,
  type CreatedSite,
  type NewPage,
  type SiteRow,
  type PageEntry,
  type SitePage,
  type SiteManifest,
  type CreateConversationInput,
  type AddCommentInput,
  type ReactionGroup,
  type CommentDTO,
  type ConversationDTO,
  type ConversationMeta,
  type PromoteConversationInput,
  type VersionSummary,
  type AddVersionInput,
  type AddedVersion,
  type MigrationCandidate,
  type ViewerSummary,
  type SiteCommentDTO,
  type ListSiteCommentsFilter,
  type TokenSummary,
  type RevokeTokenResult,
  // M10: GitHub mirror repo helpers (ADR-0008/0009).
  type MirrorRow,
  type PendingMirrorRow,
  type GitHubSiteStateRow,
  touchMirrorRow,
  bumpMirrorAttempts,
  getMirrorForComment,
  getMirrorRow,
  pendingMirrorRows,
  mirrorExistsByExternal,
  getMirrorWithOrigins,
  upsertGitHubInstallation,
  findInstallationForRepo,
  getGitHubSiteState,
  ensureGitHubSiteState,
  setGitHubReconcileCursor,
  setSiteMirrorBinding,
  findPRBackedSites,
  // M11: Postgres-backed rate limiter (ADR-0015).
  type RateLimitHit,
  hitRateLimit,
} from "./repos.js";
