// GENERATED — do not edit by hand.
// Bundles packages/bridge/src/iframe/entry.ts into an IIFE and writes the
// resulting string into src/iframe-script.generated.ts for import by inline.ts.

import * as esbuild from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const result = await esbuild.build({
  entryPoints: [join(root, "src/iframe/entry.ts")],
  bundle: true,
  format: "iife",
  minify: true,
  target: "es2020",
  write: false,
  // Prevent esbuild from treating the top-level IIFE wrapper that entry.ts
  // provides as a module — we want one self-contained IIFE.
  globalName: undefined,
  define: {},
  // tree-shake aggressively; pure annotations on Math helpers etc.
  treeShaking: true,
});

if (result.errors.length > 0) {
  for (const e of result.errors) {
    console.error(e.text);
  }
  process.exit(1);
}

let code = result.outputFiles[0].text;

// Defensive: only the literal sequence `</script` (and `<!--`) can break out of
// the inlining <script> tag. Escape the slash there. Do NOT blanket-escape every
// `</` — that corrupts regex literals in the bundled deps (e.g. diff-match-patch's
// /</g), producing an unterminated regex and a parse error that kills the script.
code = code.replace(/<\/(script)/gi, "<\\/$1").replace(/<!--/g, "<\\!--");

const out = join(root, "src/iframe-script.generated.ts");
writeFileSync(
  out,
  `// GENERATED by scripts/build-iframe.mjs — do not edit by hand.\nexport const IFRAME_SCRIPT = ${JSON.stringify(code)};\n`,
  "utf8",
);

const sizeKb = (code.length / 1024).toFixed(1);
console.log(`iframe bundle written to src/iframe-script.generated.ts (${sizeKb} KB)`);
